language: objective-c
osx_image: xcode8.3
xcode_project: PhoneComponentExample.xcodeproj
xcode_scheme: PhoneComponentExample
xcode_sdk: iphonesimulator9.3

branches:
  only:
    master

before_script:
  - cd Example_iOS7+

script: 
  - set -o pipefail
  - xcodebuild clean build test -project PhoneComponentExample.xcodeproj -scheme PhoneComponentExample -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1'